#ddev-generated
#ARG BASE_IMAGE
#FROM $BASE_IMAGE

FROM dunglas/frankenphp:1.1.2-php8.3

# add additional extensions here:
RUN install-php-extensions pdo_mysql gd intl zip xml curl json openssl mbstring apcu readline opcache

ENTRYPOINT ["/mnt/ddev_config/commands/web/frankenphp-ctl", "start"]

# See if frankenphp is running
#HEALTHCHECK --interval=1s --timeout=120s --retries=1 --start-period=120s CMD ps -p $(cat /tmp/frankenphp.pid) > /dev/null; exit $?
